README.md
rules.mk

* add VERSION to the build stamps
* add travis build badge to the README

Small tweaks

---

cmd/sidecar/main.go

I think we should use formatting mode rather than plus, do you think so? thank you!

Use formatting mode

---

cmd/sidecar-e2e/main.go

Missing check for error after ReadAll

---

images/Makefile
images/dnsmasq/Dockerfile.cross
images/dnsmasq/Makefile
images/dnsmasq/static-linking.patch
images/dnsmasq/validate.sh
rules.mk

Also adds validation in `make test` that checks that dnsmasq can
be executed.

Fix dnsmasq build (now links -static)

---

pkg/dns/dns.go

same with https://github.com/kubernetes/kubernetes/pull/38955 that not merged yet.
open a new pr here.

Use const value

---

images/dnsmasq/Makefile

Adding s390x support

---

Vagrantfile

This file will launch a Ubuntu 16.04 VM with virtualbox.
It install tools necessary to build/test DNS as well as some
dependencies like Kubernetes.
Closes #45

add vagrantfile for local development

---

images/dnsmasq/Makefile
rules.mk

https://github.com/kubernetes/dns/issues/43

Fixes pushing to registry name with ':'

---

pkg/dns/config/config.go
pkg/dns/config/config_test.go

Fixes: #68
cc  @bowei  @madhusudancs @kubernetes/sig-federation-misc

Support specifying port number for nameserver in stubDomains

---

pkg/dns/dns.go

Fix kubernetes/kubernetes#44711.
We don't have a explicit lock for `reverseRecordMap`, all the R/Ws are protected through `cacheLock`, so I followed the same pattern.
@bowei 
cc @etiennetremel

Fix race condition in reverseRecordMap access

---

build/dep.sh

Signed-off-by: Christopher M. Luciano <cmluciano@us.ibm.com>

Update dep script to support darwin

---

Godeps/Godeps.json
Makefile
build/dep.sh

Signed-off-by: Christopher M. Luciano <cmluciano@us.ibm.com>

Bump to Go version 1.8

---

rules.mk

Ack https://github.com/kubernetes/contrib/pull/2670#issuecomment-315712954.
@guirish Would you be able to test the s390x image? Thanks.
/assign @bowei 
cc @GheRivero @gajju26

Use alpine as base image on all platforms

---

cmd/e2e/main.go
pkg/e2e/docker.go
pkg/e2e/util.go

Code clean for e2e test logic. There is no functionality change. 
/cc @bowei

code clean for e2e

---

Makefile

As kubernetes already updated to 1.9.3

update go version to 1.9.3

---

cmd/dnsmasq-nanny/main.go
pkg/dns/dns.go

delete some unused parameters

---

pkg/dns/dns.go

To investigate issues easily when facing it, this commit separates
the log for each resource, services and endpoints.
fixes: #196

Separate the initialization logs for each resource

---

Makefile
build/test.sh

Signed-off-by: Christopher M. Luciano <cmluciano@us.ibm.com>

Bump build image to go 1.10.3

---

images/dnsmasq/Makefile
rules.mk

Fixes #263 .
/assign @prameshj

Bump alpine base image to 3.8.1

---

images/dnsmasq/Makefile
rules.mk

Triggered by https://github.com/kubernetes/kubernetes/issues/69104#issuecomment-424799217

Purge the manifest after the push

---

Dockerfile.node-cache
cmd/node-cache/Corefile
cmd/node-cache/main.go

Addressed review comments from https://github.com/kubernetes/dns/pull/270

Follow up changes to node-cache PR

---

cmd/node-cache/main.go
pkg/netif/netif.go

This is useful when implementing HA option as documented [here](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190424-NodeLocalDNS-beta-proposal.md#design-details)

Allow multiple listen ip addrs for node-cache

---

pkg/dns/dns.go

* Fix golint error, if block ends with a return statement, so drop this else and outdent its block

Normalize function return, if block ends with a return statement, so so drop this else and outdent its block

---

images/dnsmasq/Makefile
rules.mk

Verified that this works when pushing to gcr.io registry.

Use docker push to push images in all cases

---

pkg/sidecar/server.go

Fixed source of crash looping of DNS in case of dnsmasq connection failures. 
While working on some networking issues within some clusters I noticed one of the dns pods was crash looping:
```stderr
...
127.0.0.1:58737->127.0.0.1:53: read: connection refused
W0115 22:13:33.013395       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:41583->127.0.0.1:53: read: connection refused
W0115 22:13:38.013747       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:56871->127.0.0.1:53: read: connection refused
W0115 22:13:43.014078       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:37919->127.0.0.1:53: read: connection refused
W0115 22:13:48.018356       1 server.go:64] Error getting metrics from dnsmasq: read udp …
```

Fixed negative Prometheus counter panic in DNS sidecar. 

---

cmd/node-cache/app/cache_app.go

Use the same setup call for the initial setup as well as the periodic checks in node-cache.

Reuse the setup networking function in node-cache.

---

Makefile
README.md
cloudbuild.yaml

Updated the image registry for pushing dns images.
Also updated the docs to reflect the new steps to push images.
@MrHohn @listx

Added cloudbuild.yaml to push dns images.

---

image-checks.sh

We can improve upon this to verify more aspects of the image, but this seems like a good start. 
Everytime a change is made, we can check output of this run to ensure basic image functionality works after the change.
What do you think, @MrHohn?

Added a simple script to sanity check dns images.

---

cmd/node-cache/app/configmap.go
cmd/node-cache/app/metrics.go

Improve error handling a bit and add an error metric for config templating

Add configmap error metric

---

cmd/node-cache/main.go

Fixes https://github.com/kubernetes/dns/issues/357
@semoac

Include template plugin in node-cache.

---

Gopkg.lock
vendor/github.com/coredns/coredns/plugin/pkg/fall/fall.go
vendor/github.com/coredns/coredns/plugin/pkg/upstream/upstream.go
vendor/github.com/coredns/coredns/plugin/template/README.md
vendor/github.com/coredns/coredns/plugin/template/metrics.go
vendor/github.com/coredns/coredns/plugin/template/setup.go
vendor/github.com/coredns/coredns/plugin/template/template.go

The changes were auto-generated using "dep ensure -v".
This is required after the addition in PR - https://github.com/kubernetes/dns/pull/374

Include template plugin in vendor.

---

cmd/node-cache/app/cache_app_test.go
cmd/node-cache/app/configmap.go

Also added a test yaml where the " __PILLAR__DNS__SERVER__" string is included without substitution. This should be replaced with empty string.
This is because __PILLAR__LOCAL__DNS__ includes both the listen IP for node-cache.

Declare all substitution strings as constants in node-cache

---

cmd/node-cache/main.go

Print image version when starting node-cache.

---

rules.mk

This should resolve https://github.com/kubernetes/dns/issues/386

Bump debian base image to v2.1.2

---

README.md

include build dashboard link in README.

---

cloudbuild.yaml

As per recommendation in https://github.com/kubernetes/test-infra/pull/19254#issuecomment-694992755

Use $_PULL_BASE_REF for the image tag.

---

cmd/node-cache/main.go

Add support for rewrite plugin in node-cache.
Fixes #406

Add support for rewrite plugin in node-cache

---

cmd/node-cache/app/cache_app.go
cmd/node-cache/main.go

- error string should not be capitalized
-  sort import

Fix error string should not be capitalized and sort import

---

presubmits.sh

This will be referenced by the prow job in https://github.com/prameshj/test-infra/blob/007e1d92b25e53c5474495934a732801e7a29845/config/jobs/kubernetes/sig-network/sig-network-misc.yaml#L198

Add a new presubmit script for k/dns PRs.

---

README.md
presubmits.sh

Also updated README with presubmit info.
The extra verbosity will help debug the build failure in presubmit.

Increase verbosity of presubmit script

---

presubmits.sh

This is copied over from https://github.com/kubernetes/dns/blob/master/.travis.yml, the ginkgo test is left out for now.

Add more presubmit commands to DNS Presubmit

---

presubmits.sh

Manually verified that the ginkgo install commands work on the builder image.

Include ginkgo tests in presubmit

---

Dockerfile.node-cache
cmd/node-cache/app/cache_app.go
cmd/node-cache/main.go

https://github.com/kubernetes/dns/issues/467

467 remove setupebtables option

---

README.md

Signed-off-by: RinkiyaKeDad <arshsharma461@gmail.com>
Needed for kubernetes/k8s.io#1597

replacing master with main for k/k8s.io links

---

images/dnsmasq/Makefile
rules.mk

Also updated debian-iptables.
@wespanther @MrHohn

Upgrade to debian base buster-v1.9.0 for vuln fixes.

---

rules.mk

Verified that new images start up using ./image-checks.sh

Upgrade to iptables 1.6.7 to pick up vuln fixes.

---

README.md

Add a short section on vulnerability patching.

---

cmd/node-cache/app/cache_app.go
cmd/node-cache/app/cache_app_test.go
cmd/node-cache/app/configmap.go
cmd/node-cache/app/metrics.go
cmd/node-cache/main.go

Add license text boilerplate to node-cache code

---

README.md

Update README to include command to fetch SHAs.

---

images/dnsmasq/Makefile

Update debian-base version for vuln fixes

---

images/dnsmasq/Makefile
rules.mk

Update distroless-iptables and dnsmasq versions

---

images/dnsmasq/Makefile

Fixes: https://github.com/kubernetes/dns/issues/562

Bump dnsmasq to 2.88

---

README.md
images/dnsmasq/Makefile
pkg/e2e/options.go
test/e2e/cluster/manifests/addon-manager.json
test/e2e/cluster/manifests/master.json
test/e2e/sidecar/Dockerfile.e2e

Update references from k8s.gcr.io to registry.k8s.io

---

README.md

Corrected link for External DNS
Fixes: #581

Corrected link for external dns

---

rules.mk

Update distroless-iptables image #590

---

image-checks.sh

updated image repository
