kubernetes/dns

cmd/sidecar/main.go
pkg/sidecar/dnsprobe.go
pkg/sidecar/dnsprobe_test.go
pkg/sidecar/options.go

This allows for the query to be customized. kube-dns currently does
not handle ANY queries properly.

Add record type option to --probe

---

cmd/sidecar-e2e/main.go

Fix golint issue

---

cmd/kube-dns/app/options/options.go

this pr is same with https://github.com/kubernetes/kubernetes/pull/39314 that was not merged yet before moving codes of kube-dns to here.
so i open new one.

fix kubecfg-file flag description of kube-dns

---

docs/specification.md

Original patch: https://github.com/kubernetes/kubernetes/pull/38408
Add a DNS-schema spec to create a baseline for any DNS-based
service discovery component to follow.
Rewrite describing records that must exist
Re-wrote the specification to indicate the records that must exist.
This change the behavior of a few queries that were acting something
like wildcards. For example, querying for an SRV record with the
service name and no _port._proto prefix is no longer required to
return any records.
Other minor updates to link to external references and correct typos.
Fix formatting of headless SRV answer example.
Add reference to rcode
Add numbering, cleanup non-ASCII characters, address deprecation warning

Adds DNS-schema specification

---

rules.mk

Found a bunch of exited `golang:1.7-alpine` containers on my local machine.
```
$ docker ps --all
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                     PORTS               NAMES
1bd16b284f1f        golang:1.7-alpine   "/bin/sh -c '        "   6 minutes ago       Exited (0) 6 minutes ago                       modest_goldwasser
a2c4ac382013        golang:1.7-alpine   "/bin/sh -c '        "   6 minutes ago       Exited (0) 6 minutes ago                       distracted_cray
080b878b0c86        golang:1.7-alpine   "/bin/sh -c '        "   6 minutes ago       Exited (0) 6 minutes ago                       prickly_mccarthy
6f1351502f77        golang:1.7-alpine   "/bin/sh -c '        "   12 days ago         Exited (1) 12 days ago …
```

Clean up container after build/test

---

pkg/dns/dns.go
pkg/dns/dns_test.go

Add reverse DNS records for pods' IPs to named headless services' with Pod Hosts FQDN (`<podHostName>.<serviceName>.<namespace>.svc.cluster.local`).
Original PR: kubernetes/kubernetes#38376
Resolves Issues
- kubernetes/kubernetes#26752
- kubernetes/kubernetes#33470
Spec:
**Records for a Named Headless Service**
Type: PTR
f a ready endpoint exists with IP equal to the IP of exists, and the endpoint has a non-empty hostname with value <hostname>, then a PTR record with <hostname>.<service>.<ns>.svc.<zone> will be returned.
@thockin @bowei @smarterclayton @harryge00

Reverse DNS records for named headless services

---

cmd/kube-dns/dns.go

Saw noisy logs from kube-dns on the latest k8s cluster:
```
ERROR: logging before flag.Parse: I0113 02:27:21.529444       1 dns.go:267] New service: kubernetes-dashboard
ERROR: logging before flag.Parse: I0113 02:27:21.529467       1 dns.go:267] New service: kube-dns
ERROR: logging before flag.Parse: I0113 02:27:21.529490       1 dns.go:377] Added SRV record &{Host:kube-dns.kube-system.svc.cluster.local. Port:53 Priority:10 Weight:10 Text: Mail:false Ttl:30 TargetStrip:0 Group: Key:}
ERROR: logging before flag.Parse: I0113 02:27:21.529510       1 dns.go:377] Added SRV record &{Host:kube-dns.kube-system.svc.cluster.local. Port:53 Priority:10 Weight:10 Text: Mail:false Ttl:30 TargetStrip:0 Group: Key:}
ERROR: logging before flag.Parse: I0113 02:27:21.529533       1 dns.go:267] New service: …
```

Call Parse() to avoid noisy logs.

---

Dockerfile.sidecar
Dockerfile.sidecar-e2e
rules.mk

The base image used to build the containers for the arm arch
(both arm and arm64) uses the pair nobody:nogroup while amd64
arch uses nobody:nobody

Fixed sidecar running group for arm arch

---

cmd/kube-dns/app/options/options.go
cmd/kube-dns/app/server.go
pkg/dns/config/sync.go
pkg/dns/config/sync_configmap.go
pkg/dns/config/sync_dir.go
pkg/dns/config/sync_dir_test.go

now that optional configmaps are possible, kube-dns should support pulling config from a mounted directory
this PR refactors the existing API-based configmap source and adds a directory-based source
c.f.
https://github.com/kubernetes/kubernetes/pull/36775#issuecomment-261412030
https://github.com/kubernetes/kubernetes/pull/38816
https://github.com/kubernetes/kubernetes/pull/39981

Add support for pulling config from a directory

---

cmd/kube-dns/app/options/options.go
cmd/kube-dns/app/server.go

Currently the upstream nameservers are hardcoded to be taken from
/etc/resolv.conf.
Allowing this option to be passed in can offer greater flexibility
for varying setups where kube-dns is not run within a container.

Adding an option to passthrough upstream nameservers to skydns.

---

build/dep.sh

Bash is not available in the golang container that this script runs in.

Change shebang to sh instead of bash

---

images/dnsmasq/Makefile
rules.mk

In this PR I have changed the version of "gcr.io/google_containers/kube-cross" image. The existing version has Go does not support s390x. With "v1.7.4-1" version it builds the dnsmasq binary and builds successfully for s390x. Also modified s390x support in "rules.mk" and "images/dnsmasq/Makefile"

Making k8s-dns-kube-dns and k8s-dns-dnsmasq images available for s390x

---

pkg/dns/config/config.go
pkg/dnsmasq/nanny.go

Also adds some glog flush() to ensure we see more of the log output

Use default config if none exist at startup

---

cmd/kube-dns/app/server.go

Fixes logging message
> 2017-04-07T22:56:44.901399945Z I0407 22:56:44.900224       1 server.go:70] Using configuration read from directory: /kube-dns-config%!(EXTRA time.Duration=10s)

Fix printf in cmd/kube-dns/app/server.go

---

cmd/kube-dns/dns.go
cmd/sidecar/main.go
pkg/version/version.go

Hi,
It seems that during startup the kube-dns service is reporting (static) version of kubernetes:
$ make bin/amd64/kube-dns
building : bin/amd64/kube-dns
$ bin/amd64/kube-dns 
I0317 11:24:42.981414   27628 dns.go:49] version: v1.5.2-beta.0+$Format:%h$
...
which is defined in vendor/k8s.io/kubernetes/pkg/version/base.go and seems rather wrong/useless. We should report kube-dns version instead, which is compiled-in during compile time.
After applying this fix:
$ make bin/amd64/kube-dns
building : bin/amd64/kube-dns
$ bin/amd64/kube-dns 
I0317 11:27:32.043009   30292 dns.go:49] version: 1.14.1-dirty
which looks more appropriate.
Have a nice day,
Ashley

Fix version on startup

---

pkg/dns/dns.go

The logging we have when initializing services and endpoints is confusing:
```
DNS server not ready, retry in 500 milliseconds
```
Modify the message a bit to clarify what it is doing.

Fix confusing logging when initialize server

---

cmd/kube-dns/app/server.go

When the `client-go` package was introduced, the `kube-master-url` flag was rendered unusable. With this PR, the user can now specify the master URL without having to provide a kubeconfig file.
Fixes #72

Support kube-master-url flag without kubeconfig

---

images/dnsmasq/Makefile

Fixes #86 .
This invocation should work in both BSD & Linux `sed`. Note that I remove the backup file being created.

Use BSD-compatible sed command in dnsmasq Makefile.

---

rules.mk

Without --pull, it's possible to use old base images which may have fixed vulnerabilities upstream.
x-ref kubernetes/kubernetes#47386
After merging this, we should probably re-tag and rebuild the dns images with updated base images.
@bowei

Always --pull during docker build

---

images/dnsmasq/Makefile

Updated golang dependency includes the fix for https://github.com/golang/go/issues/20040.
Updated alpine dependency includes fixes for CVE-2016-9841 and CVE-2016-9843.
Note that we should probably build a new dnsmasq image before building the rest, since dnsmasq-nanny depends on it.
@MrHohn @bowei 
x-ref https://github.com/kubernetes/kubernetes/issues/47386

Update dnsmasq image to use go1.7.6 and alpine:3.6

---

images/dnsmasq/Makefile
rules.mk

(last attempt after double checking email in github etc... if CLA is still an issue i have to give on this for now :/) .. and sorry for the noise :)

use armhf instead of armel for ARCH=arm busybox base images (Fixes #111)

---

pkg/dns/dns.go

Make record processing logging to V(3) to avoid log spam

---

Dockerfile.dnsmasq-nanny
rules.mk

dnsmasq-nanny dockerfile should honor user-specified REGISTRY instead of always using `gcr.io/google_containers`.

Fix dnsmasq-nanny dockerfile

---

cmd/sidecar/main.go

Fixes #98.
This is the same fix as #27, but in sidecar this time.

Avoid noisy logs in sidecar

---

cmd/kube-dns/app/server.go

I think it is useful for a webserver to have a pprof debug functionality.
So I add this to kube-dns.
Signed-off-by: allencloud <allen.sun@daocloud.io>

enable http pprof in kube-dns

---

cmd/sidecar/main.go

This PR will remove `break` statement from `switch` as it is useless in go. The default behavior is to `break` after a `case`.
/cc @bowei

fix go switch

---

cmd/kube-dns/app/server.go

I think the  `kube2sky` should be  `kube-dns`, so I fix it.

Fix: update `kube2sky` to `kube-dns` in comment of server.go 

---

cmd/kube-dns/app/server.go

Reverts kubernetes/dns#128 for fixing #138.

Revert "enable http pprof in kube-dns"

---

pkg/e2e/dns/dns.go

Fix #138 .
Add health check service validation before doing a query in kube-dns e2e query.
As for now, #139 has not been merged, so this PR will definitely does not pass the CI. But after #139 is merged, i will rebase this PR.
/cc @bowei @feiskyer @MrHohn

fix kube-dns e2e test for health check service

---

pkg/sidecar/server.go

This PR refactor the code to use `metricsClient` struct field instead of a local variable `client`.
/cc @bowei

code refactor

---

cmd/sidecar/main.go
cmd/sidecar/probeoptions_test.go

This change adds support for kube-dns sidecar probes that use
DNS type SRV queries.  This will allow kube-dns sidecar probes
to be configured using SRV queries such that the
configuration/manifest will be agnostic of whether kube-proxy
is operating in IPv4 vs IPv6 mode (i.e. whether kube-dns
is resolving kubernetes services to IPv4 vs IPv6 addresses).
This change will help resolve a kubeadm issue/PR that has been
filed:
kubernetes/kubernetes#51371
kubernetes/kubernetes#51378
although the approach in the above issue/PR will need to be
changed to use SRV rather than ANY type sidecar probes, since
the SkyDNS software that kube-dns uses does not support queries
of type ANY, and the maintainer believes that using SRV type
queries is a better approach. See:
skynetservices/skydns#323
Changes …

Add support for SRV probes to be IPv4/IPv6 agnostic

---

images/dnsmasq/Dockerfile.cross
images/dnsmasq/Makefile

Patches in the patches/* are applied to the dnsmasq code in
lexigraphical order.

Add ability to apply custom patches to the dnsmasq build

---

Makefile
build/build.sh
rules.mk

remove useless build volume mapping when build binaries.
By removing `-v $$(pwd)/bin/$(ARCH):/go/bin`, we can avoid an empty dir  `bin/ARCH/linux_ARCH`.
/cc @bowei

fix make file

---

cmd/kube-dns/app/server.go
cmd/kube-dns/app/server_test.go
pkg/dnsmasq/nanny.go
pkg/dnsmasq/nanny_test.go

This change fixes a couple of places in the kube-dns code where
IPv6 addresses are not being handled correctly for nameservers found
in a minion's resolv.conf file.
This change is needed in order to get kube-dns to operate in a
Kubernetes cluster that is IPv6-only. See Kubernetes issue 51371
(https://github.com/kubernetes/kubernetes/issues/51371).
fixes #147

Add support for nameservers with IPv6 addresses

---

cmd/kube-dns/app/server.go

set user-agent for client-go
before
```
client="kube-dns/v0.0.0 (linux/amd64) kubernetes/$Format"
```
after
```
client="kube-dns/1.14.4-2-g5584e04"
```
Signed-off-by: Wei Wei <weiwei.inf@gmail.com>

set user-agent

---

pkg/sidecar/metrics.go
pkg/sidecar/server.go
pkg/sidecar/server_test.go

Refactors package sidecar to use Prometheus Counters instead of Gauges. Metrics can be found in pkg/sidecar/metrics.go. Also adds a new test called server_test.go in package sidecar

Refactor to use Prometheus Counter instead of Gauge

---

pkg/sidecar/dnsprobe.go

Use exponential-sized buckets and start at a much lower interval: instead of 500 buckets from 10ms to 500ms, use 16 buckets from 0.25ms to 8 seconds.  Much more precise data with 30 times less storage.
Fixes #149 
From an offline conversation with one of the Prometheus maintainers I am told that changing the bucket set will disrupt results for one averaging period, i.e. if you display `rate(...[5m])` then your chart will be wrong for the five minutes covering the change.  But with a minimum resolution of 10ms the old data is only useful when your DNS is a bit broken, so I think this one-time loss is OK.

Better buckets for DNS probe latency

---

build/build.sh

Did a bit digging and found the CI build was broken after bumping to Go 1.9+ (https://github.com/kubernetes/dns/pull/193).
From Go 1.9 release notes, looks like command `go install ./...` will no longer matches package in vendor folder (https://golang.org/doc/go1.9#vendor-dotdotdot), which breaks our CI build because we are expecting `bin/amd64/ginkgo`.
This PR adds the vendor folder back for installing. Might not be the best choice but I think it at least works.
Fix https://github.com/kubernetes/dns/issues/203.

Fix travis: include vendor folder in build.sh

---

Godeps/Godeps.json
pkg/dns/dns.go
vendor/github.com/skynetservices/skydns/server/backend.go
vendor/github.com/skynetservices/skydns/server/server.go

This PR fixes #186.
We implement the HasSynced() interface that skydns defines. In the case that the endpoints and services have not been initally synced from the API server, skydns will now refuse the connection instead of returning NXDOMAIN.

Implement HasSynced() of skydns Backend interface

---

pkg/dns/dns.go

On delete service from namespace kube-dns get event  EndpointAdd. 
Func addDNSUsingEndpoints generate RecordsForHeadlessService in cache to service type externalName. 
After this delete from a cache, it's deleted an empty record, but a record of Entries for externalName stuck forever.
Solution: don't generate the empty record for externalName

fix bug with delete externalName service

---

cmd/kube-dns/app/server.go
pkg/dns/dns.go
pkg/dns/dns_test.go

Now skydns will be configured with resolv.conf when nameserver is empty.
Fixes#224 (https://github.com/kubernetes/dns/issues/224)
\assign @MrHohn

Fix external name not solving by reloading resolv.conf.

---

docs/specification.md

Proposing that a headless service without any ready endpoints should return `NXDOMAIN`, to match current behavior of kube-dns and CoreDNS.
I'm proposing we update the spec to match the implementation of kube-dns, because the spec was initially based on kube-dns behavior.
If we don't update the spec, then we should open bugs for kube-dns (and CoreDNS) and fix.
see #234

DNS Spec: Headless service with no ready endpoints 

---

images/dnsmasq/Makefile
rules.mk

We build and push images for various architectures, but are not
publishing a single manifest that can be used to look up the images.
test/images in main k/k repository and kube images in k/release already
publish manifests for all the image we need for e2e testing, so we
should do the same as the 2 images in this repository are part of the
conformance e2e test suite.
Change-Id: I3f923e6246fc04e4c36cb29cb5be1f40fbdcd8a4

Build and push manifests for container images

---

Dockerfile.sidecar
rules.mk

`NOBODY` and `ARG_NOBODY` were added in #31 because amd64 and the other architectures were using different base images, but its need was basically but removed in #127 when all architectures were converted to use alpine.
The names were also confusing (they apply to the group, not the user), so let's just remove them and hardcode the group in the Dockerfile again.

Remove unused NOBODY/ARG_NOBODY arg from docker build

---

pkg/dnsmasq/metrics.go

This PR fixes the DNS queries to get metrics such as `hits.bind.`
Without this change, the sidecar doesn't report `kubedns_dnsmasq_hits` or similar metrics and it produces logs like:
```
W0910 16:07:40.684579   18427 server.go:64] Error getting metrics from dnsmasq: invalid number of Answer records for hits.bind.: 0
```
It seems that Dnsmasq requires the recursive flag to respond to these queries. Using dig confirms this. 
Working:
```
dig chaos txt hits.bind.
```
Not working:
```
dig +norecurse chaos txt hits.bind.
```

Fix DNS query to get metrics from Dnsmasq

---

Gopkg.lock
Gopkg.toml
vendor/github.com/coredns/coredns/core/dnsserver/listen_go111.go
vendor/github.com/coredns/coredns/coremain/run.go
vendor/github.com/coredns/coredns/coremain/version.go
vendor/github.com/coredns/coredns/plugin/cache/README.md
vendor/github.com/coredns/coredns/plugin/cache/cache.go
vendor/github.com/coredns/coredns/plugin/errors/README.md
vendor/github.com/coredns/coredns/plugin/errors/errors.go
vendor/github.com/coredns/coredns/plugin/errors/setup.go
vendor/github.com/coredns/coredns/plugin/log/README.md
vendor/github.com/coredns/coredns/plugin/log/log.go
vendor/github.com/coredns/coredns/plugin/log/setup.go
vendor/github.com/coredns/coredns/plugin/loop/loop.go
vendor/github.com/coredns/coredns/plugin/loop/setup.go
vendor/github.com/coredns/coredns/plugin/metrics/metrics.go
vendor/github.com/coredns/coredns/plugin/metrics/setup.go
vendor/github.com/coredns/coredns/plugin/pkg/log/log.go
vendor/github.com/coredns/coredns/plugin/pkg/replacer/replacer.go
vendor/github.com/coredns/coredns/plugin/pkg/uniq/uniq.go
vendor/github.com/coredns/coredns/request/request.go

this contains a fix in the loop plugin that was incorrectly detecting a loop when upstream dns was unavailable.
coredns/coredns#2255

Upgrade CoreDNS to 1.2.6

---

cmd/kube-dns/app/server.go

Ref https://github.com/kubernetes/dns/issues/283#issuecomment-451000345, we should check the error returned by `SetDefaults()`. Error in `SetDefaults()` might lead to a broken DNS server.
/assign @bowei 
cc @thebag25

Check error for SetDefaults()

---

cmd/dnsmasq-nanny/main.go
pkg/dnsmasq/nanny.go
pkg/dnsmasq/nanny_test.go

Fixes #82 
it should work for not only kubernetes service name but also private dns record (e.g. dns.my.domain defined in GKE private dns)

allow service name for stubDomains

---

cmd/node-cache/main.go

https://github.com/kubernetes/dns/issues/282
There is sometimes a race in link creation and ip assignment.
If ip assignment is done too soon, the ip address does not persist.

Run checks before starting CoreDNS

---

Dockerfile.node-cache
rules.mk

Updated containers:kube-dns, sidecar
Context:[KEP: Rebase k8s images to distroless](https://github.com/kubernetes/enhancements/pull/900)
Test: 
1. `make images` can create the following images
staging-k8s.gcr.io/k8s-dns-sidecar-amd64 
staging-k8s.gcr.io/k8s-dns-node-cache-amd64
staging-k8s.gcr.io/k8s-dns-kube-dns-amd64
staging-k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64
staging-k8s.gcr.io/k8s-dns-dnsmasq-amd64 
2. `docker run -e <with required flags like service host/port> <Kube-DNS-IMAGE-ID>`
can successfully upstart a container.

Rebase container images from alpine to distroless.

---

images/dnsmasq/Makefile

Debian-base includes the glibc package.
Changing to debian-base mitigates the CVE issues.

Rebase dnsmasq images from busybox to debian-base.

---

Gopkg.lock
cmd/node-cache/main.go
cmd/node-cache/metrics.go

Nodelocaldns runs background checks to ensure its custom iptables rules are present. On failure, the pod restarts.
When deployed in an environment with other pods also using iptables heavily, there can be xtables lock contention. Adding a retry logic instead of exiting on first failure. 
Fixes #292

Add retry logic when iptables checks fail

---

images/dnsmasq/Makefile

In my previous [PR](https://github.com/kubernetes/dns/commit/9b9f8f21c437e455c9e4f0a31a4101e6c4e9d7bd#diff-19ad075a08a3805259532e36f128f677), the dnsmasq compile image (not base) is mistakenly configured to debian-base. However, the dnsmasq Makefile specifies the [alpine dependencies](https://github.com/kubernetes/dns/blob/master/images/dnsmasq/Makefile#L139) on installing the alpine-sdk package, so the dnsmasq image can't be built successfully.
This PR reverts the compile image change (which is not covered in the rebasing distroless image effort)

Fix the compile image of dnsmasq.

---

cmd/node-cache/main.go

This PR makes the metrics listen address, including interface, for the node cache configurable. This is required in order to actually be able to scrape those metrics, because the local IP is par design only reachable from the node the addon runs on.
The default of `127.0.0.2:9353` was chosen deliberately, as we can be very sure nothing will listen there already.
/assign @prameshj

Node cache: Make metrics listen address configurable

---

cmd/node-cache/main.go

This can be used if iptables management is being offloaded to a different daemonset.
that manages iptables and other networking setup. HA using the approach described [here](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190424-NodeLocalDNS-beta-proposal.md#design-details) becomes easier with this. All the iptables and liveness check logic resides in this other daemonset.

Add flag to skip iptables rules setup in nodecache

---

images/dnsmasq/Makefile

After the base-image change to debian, dnsmasq built with alpine libraries was running in a debian environment and
crashing due to failed dependencies. This change fixes the issue https://github.com/kubernetes/dns/issues/308
Built gcr.io/pavithrar-k8s-dev/k8s-dns-dnsmasq-nanny:1.15.3-dirty and verified that it works.

Change dnsmasq compile-image to debian.

---

Dockerfile.node-cache

This fixes the bug mentioned in kubernetes/dns#314 which in causing multi-arch builds to publish amd64 images.

Fix hardcoded base image for node-cache kubernetes/dns#314

---

cmd/node-cache/main.go

For pods running on hostNetWithClusterFirst mode, the DNS requests to nodelocaldns will be generated from host network, so they skip
the PREROUTING chain. Currently, NOTRACK rules are added in the raw PREROUTING chain. These request packets will be subject to NAT rules added by
kube-proxy if nodelocaldns uses a service ClusterIP as a listenIP.
This PR adds the NOTRACK rules to raw OUTPUT table so that locally generated requests also skip CONNTRACK.
Fixes issue https://github.com/kubernetes/dns/issues/318
I was able to verify that this works, the reporter of the issue was able to, as well.
cc @axot

Skip conntrack for DNS requests to node-cache from host

---

cmd/node-cache/app/cache_app.go
cmd/node-cache/app/cache_app_test.go
cmd/node-cache/app/configmap.go
cmd/node-cache/app/metrics.go
cmd/node-cache/main.go

This change adds functionality in node-cache to generate the Corefile based on stubDomain and upstream servers config in kube-dns config map. This requires the kube-dns configmap to be mounted in the local filesystem.
The nodelocaldns yaml will look like this - https://github.com/kubernetes/kubernetes/commit/af3316b6c4d58814d86bb4b40ebfe80ddc949659

Support kube-dns stubdomain config in node-cache

---

cmd/node-cache/app/cache_app_test.go
cmd/node-cache/app/configmap.go

When node-cache is configured with multiple -localip, the stubdomains
block in Corefile would generate "ip1,ip2" as the parameter to bind
plugin. It needs to be "ip1 ip2"
This was causing the stubdomain test to fail - https://k8s-testgrid.appspot.com/sig-network-gce#gci-gce-serial-kube-dns-nodecache
Verified that this works by running the stubdomain test manually:
./hack/ginkgo-e2e.sh --ginkgo.focus="stubDomain" --report-dir=/workspace/_artifacts --disable-log-dump=true

Fix stubDomains configblock for multiple listenip.

---

cmd/node-cache/main.go

The version hardcoded here is already out of date. This pulls the version string from the upstream package.

don't hardcode coredns version

---

docs/specification.md

Add IPv6 support to the DNS specification:
* add AAAA records for IPv6 addresses
* add IP6.ARPA domain for IPv6 reverse lookup
It also removes the section `2.6 - Deprecated Records`
because the deprecated records are IPv4 only 
Ref: https://tools.ietf.org/html/rfc3596
Fixes: #315

Add IPv6 support to the DNS specification

---

Dockerfile.sidecar

Fixes: https://github.com/kubernetes/dns/issues/321
/assign @MrHohn @prameshj

Debian base uses `nogroup` as the group

---

README.md
rules.mk

The current build docs only work for the first build.
If you:
- make build; make containers; make test
- Commit
- make build; make containers; make test
The final build will not find base images and fail.

Fix build instructions

---

cmd/node-cache/app/cache_app_test.go

The config sync interval is 10s. Sometimes the test fails since it sleeps for 10s and the sync has not happened yet.

modify cache_app_test to sleep for more time.

---

Gopkg.lock
cmd/node-cache/main.go
vendor/github.com/coredns/coredns/plugin/loadbalance/README.md
vendor/github.com/coredns/coredns/plugin/loadbalance/handler.go
vendor/github.com/coredns/coredns/plugin/loadbalance/loadbalance.go
vendor/github.com/coredns/coredns/plugin/loadbalance/setup.go
vendor/github.com/coredns/coredns/plugin/whoami/README.md
vendor/github.com/coredns/coredns/plugin/whoami/fuzz.go
vendor/github.com/coredns/coredns/plugin/whoami/setup.go
vendor/github.com/coredns/coredns/plugin/whoami/whoami.go

I'd like to enable the plugins `loadbalance` and `whoami`
- loadbalance is useful because of how consul returns records (large sets of A records which are randomized on retrieval). However, coredns doesn't randomize this set. So the records remain ordered until a new set is retrieved. I'm worried that this will cause hotspotting.
- whoami is useful because "we can add node.cluster.local as a zone that resolves to the host ip. Then we can put that value into configmaps, vs having to use downward api and hacks (since configmaps don't natively support that). Our specific use case is a node local memcached instance listening on a hostport" -@gbrayut
I've tested node-local-dns with the new plugins. It works, and the new loadbalance plugin is present.
```
apiVersion: v1
data:
Corefile: | …
```

Add loadbalance, whoami plugins

---

cmd/node-cache/app/cache_app.go
cmd/node-cache/main.go

This is useful when running multiple node-cache instances for HA.
The rules/interface shouldn't be torn down when one of them exit.

Add a flag to skip teardown in node-cache.

---

Dockerfile.node-cache
images/dnsmasq/Makefile
rules.mk

debian-iptables container transparently select iptables-legacy or iptables-nft since v12.0.0:
https://github.com/kubernetes/kubernetes/pull/82966
This fixes #338 
While at it bump debian-base from v1.0.0 to v2.0.0

Use debian-iptables-$(ARCH):v12.0.1 and debian-base-$(ARCH):v2.0.0

---

cmd/node-cache/app/cache_app.go

When using an HA setup of nodecache, it is imperative to avoid that one
instance of nodecache tear down networking at any time, to avoid disrupting
functionalities for the second instance, which is sharing the same interface
and iptables rules.
This fix addresses the issue of nodecache trying to tear down networking
at startup, right before ensuring it is setup again. When `--skipteardown`
flag is passed, nodecache should not try to do so, but instead simply
ensure that networking is correctly setup.
This should fix #358

Fix skipteardown flag not completely avoiding teardown

---

cmd/node-cache/app/metrics.go

I've noticed that `coredns_nodecache_setup_errors` metric only appears when there are errors. Ideally we would initialize it to 0 as per Prometheus best practices (https://prometheus.io/docs/practices/instrumentation/#avoid-missing-metrics, https://www.robustperception.io/existential-issues-with-metrics).
Also added total suffix as per https://prometheus.io/docs/practices/naming/#metric-names

Improve Prometheus metrics for node-cache

---

Dockerfile.node-cache
images/dnsmasq/Makefile
rules.mk

Reverts kubernetes/dns#355
This causes node-cache image to fail since iptables is not found.
@champtar i am reverting this, feel free to submit a new PR with the changes enabled.

Revert "Use debian-iptables-$(ARCH):v12.0.1 and debian-base-$(ARCH):v2.0.0"

---

Dockerfile.node-cache
images/dnsmasq/Makefile
rules.mk

Use --no-install-recommends to not install nftables as it depends on bash
(https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=956655)
Only build tested for amd64 for now
champtar/k8s-dns-sidecar-amd64         1.15.11-14-g423a2b4   b28aafaa2996
champtar/k8s-dns-node-cache-amd64      1.15.11-14-g423a2b4   bb1e2b6e0b09
champtar/k8s-dns-kube-dns-amd64        1.15.11-14-g423a2b4   943afc53b468
champtar/k8s-dns-dnsmasq-nanny-amd64   1.15.11-14-g423a2b4   28526da70d44
champtar/k8s-dns-dnsmasq-amd64         1.15.11-14-g423a2b4   a13a493a9883
Edit: update images

Use debian-base-$(ARCH):v2.0.0 as base image

---

build/build.sh

This seems to be causing automated builds to fail.
When triggering the command manually with increased verbosity, I see the log:
```
ec448270508e: Pull completeDEBUG: Reading GCS logfile: 206 (read 162 bytes)65ba82af53f7: Pull completeDigest: sha256:09e47edb668c2cac8c0bbce113f2f72c97b1555d70546dff569c8b9b27fcebd3Status: Downloaded newer image for golang:1.11-alpineDEBUG: Reading GCS logfile: 206 (read 254 bytes)VERSION must be setmake[1]: *** [rules.mk:95: bin/amd64/dnsmasq-nanny] Error 1make: *** [rules.mk:67: push-amd64] Error 2ERRORERROR: build step 0 "gcr.io/k8s-testimages/gcb-docker-gcloud:v20190906-745fed4" failed: step exited with non-zero status: 2DEBUG: Reading GCS logfile: 416 (no new content; keep polling)
```
Command used:
```
gcloud builds submit --verbosity debug --config …
```

Set version variable in build script, if not set.

---

build/build.sh

Reverts kubernetes/dns#371
This change is not required. cloudbuild needs to set the VERSION variable.

Revert "Set version variable in build script, if not set."

---

cloudbuild.yaml

This will be used to tag the new images. This will fix the "VERSION must be set" error that build scripts are seeing in https://k8s-testgrid.appspot.com/sig-network-dns#dns-push-images

Add a VERSION env var in cloudbuild.

---

images/dnsmasq/Makefile

This is needed for the check to pass in sha256sum installed in Busybox.
Verified that the automated build works using the command:
```
gcloud builds submit ~/src/k8s.io/dns --verbosity debug --config cloudbuild.yaml --substitutions _PULL_BASE_REF=master,_GIT_TAG=v20200416-1.15.12-2-g232a189 --project k8s-staging-dns --gcs-log-dir gs://k8s-staging-dns-gcb/logs --gcs-source-staging-dir gs://k8s-staging-dns-gcb/source
```
The build above succeeded.
Thanks to @listx for identifying the correct command to be used in the build environment!

Add extra space in sha check command

---

images/dnsmasq/Makefile
rules.mk

Use the new debian-base image published to us.gcr.io/k8s-artifacts-prod instead of the old location

chore(Makefile): update base image

---

Dockerfile.node-cache
Gopkg.lock
cmd/node-cache/app/cache_app.go
cmd/node-cache/main.go
vendor/k8s.io/utils/LICENSE
vendor/k8s.io/utils/exec/README.md
vendor/k8s.io/utils/exec/doc.go
vendor/k8s.io/utils/exec/exec.go
vendor/k8s.io/utils/inotify/LICENSE
vendor/k8s.io/utils/inotify/PATENTS
vendor/k8s.io/utils/net/ebtables/ebtables.go
vendor/k8s.io/utils/third_party/forked/golang/LICENSE
vendor/k8s.io/utils/third_party/forked/golang/PATENTS

Add extra `ebtables` option to NodeLocalDNS to address issue related to Azure Kubernetes (AKS):
https://github.com/kubernetes/dns/issues/389
This option, when true (default is false), adds the following 2 ebtables rules to nodes when NodeLocalDNS is installed:
```
sudo ebtables -t broute -A BROUTING --ip-dst 169.254.20.10 -p IPv4 -j redirect
sudo ebtables -t broute -A BROUTING --ip-dst 10.0.0.10 -p IPv4 -j redirect  
```
where the 2 IPs are from the -localip argument passed to NodeLocalDNS.
The 2 rules are automatically removed during NodeLocalDNS tear down as it happens already for iptables rules.

Nodecache ebtables option

---

cmd/node-cache/app/cache_app.go

For deployments where node-cache is non listening on kube-dns IP, the kube-dns-upstream
service is not relevant. This change adds a warning message instead of a fatal error.

Log warning if kube-dns-upstream is not found.

---

cmd/node-cache/app/cache_app_test.go
cmd/node-cache/app/configmap.go

https://github.com/kubernetes/kubernetes/pull/93471 replaces the force_tcp block. So, it is expected for upstream block to not have TCP anymore.
Replacing TCP upstream block to UDP can fail if the existing config was
already using UDP.  Fix warning message to capture this.

Fix warning message in node-cache when replacing custom upstream server

---

cmd/node-cache/app/cache_app.go
cmd/node-cache/main.go

This is to support cases where we need to deploy node-local-dns as non-host pods.

Adds option to NOT set up interface when deployed in non-root ns.

---

images/dnsmasq/Makefile

Follow up from https://github.com/kubernetes/dns/pull/411
Verified that the images built correctly and start up:
```
./image-checks.sh 1.15.15-11-g90a259a gcr.io/pavithrar-k8s-dev
Verifying dnsmasq-nanny startup
Unable to find image 'gcr.io/pavithrar-k8s-dev/k8s-dns-dnsmasq-nanny:1.15.14' locally
1.15.14: Pulling from pavithrar-k8s-dev/k8s-dns-dnsmasq-nanny
Digest: sha256:7cc4fed7134eb27f580be1acb6b3492f840d8f6f21fde37b0d24c24c59f09988
Status: Downloaded newer image for gcr.io/pavithrar-k8s-dev/k8s-dns-dnsmasq-nanny:1.15.14
F1008 18:51:34.832546       1 nanny.go:220] dnsmasq exited: <nil>
goroutine 1 [running]:
k8s.io/dns/vendor/github.com/golang/glog.stacks(0xc000333100, 0xc000414000, 0x42, 0x95)
/go/src/k8s.io/dns/vendor/github.com/golang/glog/glog.go:769 +0xd4 …
```

Update the compile image to debian v2.1.2

---

Dockerfile.kube-dns
Dockerfile.node-cache
Dockerfile.sidecar
images/dnsmasq/Makefile
rules.mk

debian-iptables container transparently select iptables-legacy or iptables-nft since v12.0.0:
kubernetes/kubernetes#82966
This fixes #338

Use debian-iptables for k8s-dns-node-cache, bump debian-base version

---

cmd/node-cache/app/configmap.go
cmd/node-cache/main.go

For upgrade user, it is odd that the logs shows that /etc/kube-dns file missing.
Corefile is required, however, stubdomain is not.
So we should not set the /etc/kube-dns as the default value, we can check it and load it if it exists. 
That's why I add this pr.
The kube-dns configmap mount is optional, and when we create it after the pod start, the file will appear after the config map is created.

check default kube-dns cm file path firstly

---

cmd/node-cache/main.go

Add support [hosts](https://coredns.io/plugins/hosts/) plugin for node-cache.
It enable coredns's hosts plugin so user can add custom hosts to cluster.
Fixes kubernetes-sigs/kubespray/issues/6676

Add support hosts plugin for node-cache

---

cmd/node-cache/main.go

Add trace coredns plugin to node-cache.
Fixes #423.

Add coredns trace plugin to node-cache.

---

cmd/node-cache/app/cache_app.go

It seems like exitchan output is useless, so struct type may be more available

Trans exitchan elm type to struct

---

images/dnsmasq/Makefile

https://www.jsof-tech.com/disclosures/dnspooq
Verified that the images all come up correctly.
```
/image-checks.sh 1.16.0-18-g6f0a02c-dirty gcr.io/<repo>
1.16.0-18-g6f0a02c-dirty: Pulling from <repo>/k8s-dns-dnsmasq-nanny
Status: Downloaded newer image for gcr.io/<repo>/k8s-dns-dnsmasq-nanny:1.16.0-18-g6f0a02c-dirty
I0120 00:42:19.372813       1 main.go:78] opts: {{/usr/sbin/dnsmasq [] false} /etc/k8s/dns/dnsmasq-nanny 10000000000 127.0.0.1:10053}
I0120 00:42:19.373466       1 nanny.go:124] Starting dnsmasq []
W0120 00:42:19.390982       1 nanny.go:150] Got EOF from stdout
W0120 00:42:19.391000       1 nanny.go:150] Got EOF from stderr
F0120 00:42:19.391066       1 nanny.go:220] dnsmasq exited: <nil>
```

Upgrade to dnsmasq 2.83 to pick up vulnerability fix

---

cloudbuild.yaml

The previous build invocation failed due to timeout - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/dns-push-images/1352431660452286464

Increase build timeout to 1.5 hours.

---

rules.mk

Per https://github.com/kubernetes/k8s.io/pull/1559
debian-iptables  is built on new debian-base 1.3.0.

update debian-iptables to buster-v1.4.0 for base change debian-base

---

images/dnsmasq/Makefile

Reverts kubernetes/dns#431
Some DNS lookup errors have been reported in http://lists.thekelleys.org.uk/pipermail/dnsmasq-discuss/2021q1/014621.html
Will pick up the latest once the fixed version is available.

Revert "Upgrade to dnsmasq 2.83 to pick up vulnerability fix"

---

images/dnsmasq/Makefile
rules.mk

https://github.com/kubernetes/kubernetes/pull/98526
Bump debian-base to v1.4.0 and debian-iptables to v1.5.0 
The last update is not completed. So I need to update it.

update debian image tag 1.4.0

---

images/dnsmasq/Makefile
rules.mk

There are several vulnerabilty fixes betwen buster-v1.5.0 and
buster-v1.6.0.
Verified that all images start up using ./image-checks.sh

Update iptables and base images to buster-v1.6.0.

---

cmd/node-cache/app/cache_app.go
cmd/node-cache/app/cache_app_test.go
cmd/node-cache/main.go

Fixes #448 
This add an initial call to setupNetworking before we start the loop in order to avoid waiting SyncInterval for initial setup.

Avoid delaying startup by SyncInterval for initial iptables/ebtables setup

---

cloudbuild.yaml

Current builds are failing due to timeout - https://k8s-testgrid.appspot.com/sig-network-dns#dns-push-images

Increase build timeout to 2 hours.

---

images/dnsmasq/Makefile

Vulnerability fixed in 2.83 also introduced a DNS failure issue.
This persisted in 2.84, but should be resolved in 2.85.
See #431, #440 for context.
From [dnsmasq changelog](https://thekelleys.org.uk/dnsmasq/CHANGELOG):
> Fix problem with DNS retries in 2.83/2.84.
Pulling assignees from previous PRs.
/assign MrHohn bowei
/cc prameshj
/hold From the previous PRs, it looks like we have to give Travis some time to spin up?

Upgrade to dnsmasq 2.85.

---

images/dnsmasq/Makefile
rules.mk

debian-base:buster-v1.7.2
debian-iptables:buster-v1.6.3
This is in order to pick up vulnerability fixes.
Tested images start with image-checks.sh.

Update debian-iptables and debian-base images.

---

images/dnsmasq/Makefile
rules.mk

Verified with ./images-check.sh that the amd64 images are starting up.
```
Verifying that iptables exists in node-cache image
iptables v1.8.5 (legacy): no command specified
Try `iptables -h' or 'iptables --help' for more information.
Verifying that node-cache binary exists in node-cache image
2021/07/02 21:06:14 [INFO] Starting node-cache image: 1.19.0-dirty
2021/07/02 21:06:14 [FATAL] Error parsing flags - invalid localip specified - "", Exiting
Verifying dnsmasq-nanny startup
I0702 21:06:15.359415       1 main.go:78] opts: {{/usr/sbin/dnsmasq [] false} /etc/k8s/dns/dnsmasq-nanny 10000000000 127.0.0.1:10053}
I0702 21:06:15.359529       1 nanny.go:124] Starting dnsmasq []
W0702 21:06:15.370098       1 nanny.go:150] Got EOF from stdout
W0702 21:06:15.370099       1 nanny.go:150] Got EOF …
```

update debian base for vuln fixes.

---

cmd/node-cache/app/cache_app.go
cmd/node-cache/app/metrics.go

This will help identify any teardown errors when nodelocaldns pod is exiting.
No unit test since fake iptables in https://github.com/kubernetes/kubernetes/blob/master/pkg/util/iptables/testing/fake.go does not return error in any of the calls. This needs to be enhanced to verify error scenarios.
/assign @MrHohn 
/cc @rtheis

Increment error metric for rule deletion errors as well.

---

parse-image-sha.py

This can be used to generate the diff for promoting images in https://github.com/kubernetes/k8s.io/tree/main/k8s.gcr.io/images/k8s-staging-dns

Add a new script to parse image shas for new tags.

---

presubmits.sh

Current presubmit shows a "pass" status even if the build fails. Example - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/dns/495/pull-kubernetes-dns-test/1473729632233590784

Fail presubmit if any of the build commands fail.

---

Makefile
cmd/e2e/main.go
cmd/kube-dns/app/server.go
pkg/tools/tools.go

https://access.redhat.com/security/cve/cve-2021-39293 - does not appear relevant to the DNS images, but upgrading as a best-practice.

Upgrade to golang 1.17 to pick up CVE fix.

---

pkg/dns/dns.go
pkg/dns/dns_test.go
pkg/dns/util/util.go

Usage of the Service.Spec.ClusterIPs field is needed for Dual-Stack clusters

Use ClusterIPs field to create DNS records

---

rules.mk

Fixes:
CVE-2022-2068
CVE-2022-1664

Bump debian iptables image version for vuln fixes

---

images/dnsmasq/Makefile
images/dnsmasq/validate.sh
images/dnsmasq/validate_dynamic_deps.py

The multi-arch build for the dnsmasq container was broken for ARM (and other non x86 architectures) after migrating to a distroless base in https://github.com/kubernetes/dns/commit/6c92fb0912575e1048c87b1ea51058ef940b639d. All of the dynamic dependencies included for dnsmasq were formatted for x86 machines
This PR should fix the problem by using `docker buildx` instead of `docker`.
This is the output for the bad 1.22.5 image, and the image built from my fix (It's tagged with -dirty).
New good image built locally:
```
❯ IMAGE=gcr.io/k8s-staging-dns/k8s-dns-dnsmasq-arm64:1.22.5-dirty ./validate.sh
Checking gcr.io/k8s-staging-dns/k8s-dns-dnsmasq-arm64:1.22.5-dirty 
Analyzing the binary /usr/sbin/dnsmasq from gcr.io/k8s-staging-dns/k8s-dns-dnsmasq-arm64:1.22.5-dirty
Dependencies:
libc.so.6 …
```

Fix multi arch build and improve images/dnsmasq/validate.sh

---

cloudbuild.yaml
rules.mk

In README https://github.com/kubernetes/test-infra/blob/b74506333229b4cecfddccded988e80f5742e4b3/config/jobs/image-pushing/README.md
it's said to set HOME var for the docker buildx build

Update cloudbuild.yaml to run docker buildx

---

cloudbuild.yaml

From recent run:
https://storage.googleapis.com/kubernetes-jenkins/logs/dns-push-images/1549347853271306240/build-log.txt
```
pushing  : gcr.io/k8s-staging-dns/k8s-dns-dnsmasq-nanny-amd64:master
unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
make[1]: *** [rules.mk:165: .gcr.io_k8s-staging-dns_k8s-dns-dnsmasq-nanny-amd64_master-push] Error 1
```

Add docker auth command in cloudbuild to push images

---

cmd/node-cache/app/cache_app_test.go
cmd/node-cache/app/configmap.go
pkg/dns/config/config.go
pkg/dns/config/config_test.go

The validation is ported from the CoreDNS plugin forward: https://github.com/coredns/coredns/blob/fc7f3835d506960364b21cf62116a70eb8f4caf2/plugin/forward/setup.go#L97
TESTED= make bulid; make containers; make test (with the broken validate_dynamic_deps.py skipped)
Fix: #539

Add extra config validation in node-local-cache config sync

---

cmd/node-cache/app/cache_app_test.go
cmd/node-cache/app/configmap.go
cmd/sidecar-e2e/main.go
pkg/dns/config/sync_dir.go
pkg/dns/config/sync_dir_test.go
pkg/dns/dns_test.go
pkg/e2e/dnsmasq/nanny.go
test/e2e/kubedns/kubedns.go
third_party/forked/skydns/server/metrics_test.go

The `io/ioutil` package has been deprecated in Go 1.16 (See https://pkg.go.dev/io/ioutil). This PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.
- `ioutil.Discard` => `io.Discard`
- `ioutil.NopCloser` => `io.NopCloser`
- `ioutil.ReadAll` => `io.ReadAll`
- `ioutil.ReadDir` => `os.ReadDir`
- `ioutil.ReadFile` => `os.ReadFile`
- `ioutil.TempDir` => `os.MkdirTemp`
- `ioutil.TempFile` => `os.CreateTemp`
- `ioutil.WriteFile` => `os.WriteFile`
`ioutil.TempDir` in `*_test.go` files can be replaced with `t.TempDir` from the `testing` package. The directory created by `t.TempDir` is automatically removed when the test and all its subtests complete. 
Reference: https://pkg.go.dev/testing#T.TempDir

refactor: move from io/ioutil to io and os packages

---

rules.mk

This registry claims to fix new vulnerabilities quicker than the upstream.
If it will turn out unsuitable in the future we could always return back to k8s registry.

Switch distroless-iptables to gke-release

---

cloudbuild.yaml

The build for all images for all supported arch takes ~1h50min and it may not fit the current 2h sometimes.  https://github.com/kubernetes/dns/issues/564#issuecomment-1372030269
One of the options is to investigate if the build parallelisation would decrease the build time, but that's not a priority and may be would be done later.

Increase build timeout

---

images/dnsmasq/Makefile
images/dnsmasq/validate_dynamic_deps.py
rules.mk

To address vulnerabilities:
1. CVE-2022-2097
2. CVE-2022-4304
3. CVE-2023-0286
4. CVE-2022-4450
5. CVE-2023-0215
Fixes #572

Update distroless-iptables and base-debian11 images

---

README.md

I like others (https://github.com/kubernetes/dns/issues/487) were wondering if there is any incompatibility between the containers in this repo and k8s releases but it's not clear from the main README. So here I'm adding a note to make it clear as looking for version compatibility issues is now a large part of managing the lifecycle of k8s clusters and their components 🙂

Update README, add note about k8s version compatibility

---

README.md

Updated link for kube-dns in [README.md](https://github.com/kubernetes/dns/blob/master/README.md)

Link update for kube-dns

---

README.md

**What type of PR is this?**
/kind cleanup
**What this PR does / why we need it:**
Fixes a  broken link to testgrid dashboard in README.md
**Which issue(s) this PR fixes:**
This is related to an umbrella issue and fixes a task of the same:
https://github.com/kubernetes/test-infra/issues/30370

fix broken links to testgrid dashboard

---

Makefile
go.mod
go.sum
third_party/forked/skydns/Gopkg.lock
vendor/modules.txt

fixes for Vulnerabilities: CVE-2023-29409, CVE-2023-39533, CVE-2023-29406

upgrate go to 1.20.7 and remove hardcoded crypto version

---

pkg/e2e/cluster.go

The existing E2E tests don't need kubelet (proven as this commit still
passing presubmit), while the execution of kubelet started to cause
mysterious failures recently (#605). Let's exclude kubelet in the mock
cluster for now. Not completely removing the relevant code in case some
future tests need them, then #605 can be investigated at that time.

Don't run kubelet in the E2E test mock cluster

---

images/dnsmasq/Makefile

Bumping from `sha256:73deaaf6a207c1a33850257ba74e0f196bc418636cada9943a03d7abea980d6d` from `Jun 2` to `b31a6e02605827e77b7ebb82a0ac9669ec51091edd62c2c076175e05556f4ab9` from `Oct 31`.

Bump debian BASEIMAGE for dnsmasq to fix vulnerabilities

---

images/dnsmasq/Makefile

The new dnsmasq version is officially released. Among other things, it 
* enables increasing the number of concurrent TCP connections, previously hardcoded as 20,
* fixes the bug causing memory leaks for records with TTL=0.

Upgrade to dnsmasq v2.90

---

rules.mk

This fixes the CVE-2023-5363 and CVE-2023-5528 mentioned in the issue #620

Vuln fixes for CVE-2023-5363 and CVE-2023-5528

---

rules.mk

Upgrading base images as discussed in #620.
In this change, the base image is upgraded to `Debian 12` and the IPT image to `v0.5.3`, the latest release of distroless-iptables.
<details>
<summary>Available distroless-iptables tags</summary>
```bash
skopeo list-tags docker://registry.k8s.io/build-image/distroless-iptables
{
"Repository": "registry.k8s.io/build-image/distroless-iptables",
"Tags": [
"sha256-0083d9e4ebc9581f604f6bb68dd97c115293c7fba38fa5d249309fb99da33652.sig",
"sha256-13ac9b3c476d7290a4451d65d09d6016a2cb89836ffbfa4eae55b72731a22080.sig",
"sha256-146e96c6b3349b46fcbcdd354be4b8db7a28915be9b0b46c01537ced8912989a.sig",
"sha256-17282b8c158e7efe33a6ff21eae36a9b6a39c49db2b2376af2c5917b1ca4efdf.sig",
"sha256-33ea7b61b3dda4323872a7a726e4753ec6848c38faadb6776af950f4fc0c4507.sig", …
```

refactor: upgrade base images version for vuln fixes

---

Makefile
go.mod

go lang version 1.22 is required by k8s.io/kubernetes in vendor/modules.txt.

Update go version to 1.22

---

README.md

This is to avoid mistakes like I just did creating https://github.com/kubernetes/k8s.io/pull/6860 and only realising I'm editing a wrong file after pushing a PR.

Correct link to images.yaml in README from k8s.gcr.io to registry.k8s.io

---

pkg/e2e/cluster.go
pkg/e2e/dns/dns.go
pkg/e2e/options.go
test/e2e/cluster/manifests/addon-manager.json
test/e2e/cluster/manifests/master.json
test/e2e/kubedns/kubedns.go
test/e2e/sidecar/Dockerfile.e2e

- Update the out of date images used for E2E testing. 
- Remove incorrectly named and deprecated flags
https://github.com/kubernetes/dns/issues/646

Update e2e test images, fix test timeouts

---

README.md

This adds to the release instructions in `README.md` that a presubmit
should be triggered before bumping kubedns or nodecache (`cluster/addons/dns/`) versions in
kubernetes/kubernetes and the test grid https://testgrid.k8s.io/sig-network-gce#gci-gce-serial-kube-dns (and other related tabs) should be verified afterwards. This should prevent issues like https://github.com/kubernetes/kubernetes/pull/123590 and https://github.com/kubernetes/kubernetes/issues/129230 from happening in the future and/or speed up their detection.

docs: Presubmit triggering and grid validation in README#Release process

---

rules.mk

Bumps version of the iptables image to remediate vulns.
Fixes:
- CVE-2023-5678
- CVE-2023-6129
- CVE-2023-6237
- CVE-2024-0727
- CVE-2024-4603
- CVE-2024-4741
- CVE-2024-5535
- CVE-2024-6119
- CVE-2024-2511
- CVE-2024-9143

chore: update base iptable image to remediate vulns

---

cmd/dnsmasq-nanny/main.go
pkg/dnsmasq/nanny.go
pkg/dnsmasq/nanny_test.go
test/fixtures/mock-dnsmasq.sh

This adds a feature flag `--logInterval` for periodic triggering dnsmasq to log its statistics by sending `SIGUSR1` to it.
The new motivation for adding this feature comes from dnsmasq changes in `v2.90`: the new [flag](https://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=commit;h=416390f9962e455769aa8ab6df0e105cae07ae55) `--max-tcp-connections`and the related [statistics](https://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=commit;h=69877f565a969260cf2761b2fd512d6c28dbf2f0) of TCP connection utilisation added to the log output triggered by `SIGUSR1`.
The change was benchmarked (see the commit description) and no negative impact was observed.

Send SIGUSR1 to dnsmasq periodically

---

rules.mk

Update Debian image:
-  from 12.8 (gcr.io/distroless/static-debian12@sha256:f4a57e8ffd7ba407bdd0eb315bb54ef1f21a2100a7f032e9102e4da34fe7c196) 
- to 12.10 (gcr.io/distroless/static-debian12@sha256:765ef30aff979959710073e7ba3b163d479a285d7d96d0020fca8c1501de48cb) version
Debian 12.10 ([release notes](https://www.debian.org/News/2025/20250315)) includes security fixes for CVE-2025-0395 and several others.

Update distroless static-debian12 image

---

images/dnsmasq/Makefile
rules.mk

followup to #685
distroless-iptables contains the fix for CVE-2025-0395 in node-cache image
base-debian12 contains the fix for CVE-2025-0395 in dnsmasq-nanny image
At this point I'm afraid to ask what's the difference between base-debian and debian-base, but it seems like bumping the amd64 COMPILE_IMAGE is also the right thing to do

Bump base images

---

.github/dependabot.yml

https://github.com/kubernetes/dns/issues/691 
While Dependabot doesn't parse image versions directly from Makefiles (e.g., `BUILD_IMAGE`), requiring manual updates for those, its automated PRs are crucial. They notify maintainers of new Go or Dockerfile versions, accelerating the update process and reducing manual effort. Dependabot's groupe updates further improve dependency management efficiency, even if some Makefile-defined versions still need manual attention.
Tags are used to improve classification of created PRs.

Enhance dependabot configuration

---

.github/dependabot.yml

Follow up on https://github.com/kubernetes/dns/issues/691 on top of https://github.com/kubernetes/dns/pull/696 based on the discussion in https://github.com/kubernetes/dns/pull/697.

Configure dependabot with two groups: k8s and non-k8s, where k8s only bumps patch version

---

.github/dependabot.yml

This fixes the omission described in https://github.com/kubernetes/dns/issues/691#issuecomment-2949727895.

Add missing k8s.io/kubernetes to the k8s.io group in dependabot config

---

rules.mk

Upgrade the distroless-iptables image to version 0.6.12, based on Debian 12.11, to address various CVEs including CVE-2024-13176. 
The complete list of security fixes in the Debian 12.11 release notes is available at: https://www.debian.org/News/2025/20250517

Bump distroless-iptables to v0.6.12

---

cmd/node-cache/app/cache_app.go
cmd/node-cache/app/configmap.go
cmd/node-cache/main.go

When the nodelocaldns addon is applied during a cluster upgrade, there is a risk of deadlock. Consider the following run:
1. node-local-dns ConfigMap is updated.
2. node-cache binary receives the update, writes a new Corefile.
3. CoreDNS's reload plugin picks up the new Corefile and begins to set up a new server instance.
4. node-local-dns DaemonSet is updated.
5. node-local-dns Pod receives SIGTERM with 30s grace period. It begins executing shutdown callbacks, locking instancesMu. One of the callbacks is sending to reload plugin's unbuffered `exit` channel to make its goroutine exit.
6. reload plugin finishes setting up a new server instance, and tries to Stop() the original instance. This requires the instancesMu mutex. instancesMu is locked and to unlock it, reload plugin would have to …

Add option for node-cache to reload in-process CoreDNS via a signal.
